image: node:18

pipelines:
  default:
    - step:
        name: Test Frontend
        caches:
          - node
        script:
          - cd frontend
          - npm ci
          - npm run lint
          - npm run build
        artifacts:
          - frontend/dist/**

  branches:
    main:
      - step:
          name: Build with Kaniko
          image: gcr.io/kaniko-project/executor:debug
          script:
            - mkdir -p /kaniko/.docker
            - echo "{\"auths\":{\"riverjin839/node-labeling-mgmt\":{\"auth\":\"$(echo -n $REGISTRY_USER:$REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
            - export GIT_COMMIT=${BITBUCKET_COMMIT:0:7}
            - /kaniko/executor
              --context $BITBUCKET_CLONE_DIR/frontend
              --dockerfile $BITBUCKET_CLONE_DIR/frontend/Dockerfile.frontend
              --destination riverjin839/node-labeling-mgmt/node-labeling-mgmt-frontend:$GIT_COMMIT
              --destination riverjin839/node-labeling-mgmt/node-labeling-mgmt-frontend:latest
              --cache=true

      - step:
          name: Deploy to Kubernetes
          image: alpine:latest
          script:
            - apk add --no-cache curl bash
            - curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
            - chmod +x kubectl && mv kubectl /usr/local/bin/
            - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            - mkdir -p ~/.kube
            - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
            - helm upgrade --install node-labeling-app ./helm/node-labeling-app
              --namespace node-labeling
              --create-namespace
              --set frontend.image.repository=riverjin839/node-labeling-mgmt/node-labeling-mgmt-frontend
              --set frontend.image.tag=${BITBUCKET_COMMIT:0:7}
              --wait --timeout=600s
